using System.Text.Json.Nodes;
using WgcLiveHarness;

static class ContentEvidenceChecks
{
    public static void Run(string root, Func<long, long, CaptureDeliveryProof> fixture)
    {
        Directory.CreateDirectory(root);
        void Check(bool value, string name) { if (!value) throw new Exception(name); Console.WriteLine("PASS: " + name); }
        // Expected coordinates are the existing Python layout contract, not generated by this hash.
        foreach (var (w, h, expected) in new[] {
            (1920, 1080, (1315, 211, 1915, 847)), (1280, 720, (876, 141, 1276, 564)),
            (1920, 1200, (1315, 271, 1915, 907)), (2560, 1080, (1635, 211, 2235, 847)) })
            Check(DeliveryVisualSummary.ScrollContentBox(w, h) == expected, $"mapped protected domain {w}x{h}");
        var p = fixture(1, 100_000_000_000);
        var pixels = new byte[1920 * 1080 * 4];
        DeliveryVisualSummary Summary() => DeliveryVisualSummary.From(new(1920, 1080, 7680, pixels,
            p.ReadbackCompletedNs, "offline", p.SourceNs, 1, p));
        var original = Summary();
        void Change(int x, int y) { pixels[(y * 1920 + x) * 4] ^= 1; }
        Change(1730, 1000); var countdown = Summary(); Change(1730, 1000);
        Check(original.ScrollContentRoiSha256 == countdown.ScrollContentRoiSha256, "countdown excluded from scroll content");
        Check(original.WarehouseRoiSha256 != countdown.WarehouseRoiSha256, "advice warehouse hash still includes countdown");
        Check(DeliveryAdviceQualification.Evaluate(p, original, original, p.ReadbackCompletedNs + 1).Qualified,
            "unchanged advice support qualifies");
        Check(!DeliveryAdviceQualification.Evaluate(p, countdown, original, p.ReadbackCompletedNs + 1).Qualified,
            "countdown still vetoes advice exactly as before");
        foreach (var (x, y, name) in new[] { (1365, 255, "grid"), (1335, 748, "dark cell"),
            (1495, 335, "possible badge"), (1876, 775, "clipped edge"), (1887, 440, "scrollbar") }) {
            Change(x, y); Check(Summary().ScrollContentRoiSha256 != original.ScrollContentRoiSha256, name + " protected at one channel level");
            Change(x, y);
        }
        Change(100, 160); Check(Summary().SceneRoiSha256 != original.SceneRoiSha256, "scene identity remains protected"); Change(100, 160);

        foreach (var kind in new[] { "countdown", "content", "scene", "missing" }) {
            long now = 100_000_000_000; var events = new List<JsonObject>(); var logs = new List<JsonObject>(); var calls = 0;
            DeliveryVisualSummary? latest = null;
            using var lease = new WarehouseEvidenceLease(Path.Combine(root, kind), "offline", events.Add, () => now,
                scrollDown: (_, _) => { calls++; return false; }, capturePolicy: CapturePolicy.Delivery,
                latestSummary: () => latest, scrollDiagnosticLog: logs.Add);
            var target = new JsonObject { ["targetHwnd"] = 123L };
            lease.UpdateContext(new("r", target, "map", 1920, 1080, true, true, now + 70_000_000_000, 1));
            JsonObject Command(string op, int ordinal = 0) => new() {
                ["type"] = WarehouseEvidenceLease.ControlType, ["schemaVersion"] = WarehouseEvidenceLease.SchemaV2,
                ["operation"] = op, ["commandId"] = Guid.NewGuid().ToString("N"), ["nonce"] = "n" + ordinal,
                ["observationSessionId"] = "offline", ["reviewSessionId"] = "review", ["reviewGeneration"] = 1,
                ["recordStableKey"] = "r", ["matchGeneration"] = 1L, ["expectedTargetInstance"] = target.DeepClone(),
                ["leaseToken"] = lease.LeaseToken, ["remainingPages"] = 16, ["remainingPngBytes"] = 64L * 1024 * 1024,
                ["pngEncoding"] = WarehouseEvidenceLease.PngEncoding, ["requestOrdinal"] = ordinal, ["allowWindowScroll"] = true };
            lease.Handle(Command("OPEN"));
            JsonObject? saved = null; var proofs = new List<CaptureDeliveryProof>();
            for (var seq = 1; seq <= 2; seq++) {
                lease.Handle(Command("REQUEST_PAGE", seq)); var gate = lease.PendingRequestGateNs!.Value;
                var proof = fixture(seq, gate); proofs.Add(proof); now = proof.ReadbackCompletedNs + 1;
                pixels[0] = (byte)seq; // independent SOURCE originals; outside all protected regions
                latest = DeliveryVisualSummary.From(new(1920, 1080, 7680, pixels, now, "offline", proof.SourceNs, seq, proof));
                Check(lease.TryPublish(new(1920, 1080, 7680, pixels, proof.SourceNs, proof.ReadbackCompletedNs,
                    "offline", seq, "", seq, proof, latest, gate, 1), () => true), kind + " saves support");
                saved = (JsonObject)events.Last()["source"]!;
                var ack = Command("ACK_SOURCE", seq);
                foreach (var key in new[] { "sourceLeaseId", "bmpSha256", "pixelSha256" }) ack[key] = saved[key]!.DeepClone();
                ack["result"] = "SAVED"; lease.Handle(ack); now += 500_000_000;
            }
            if (kind == "countdown") latest = latest! with { WarehouseRoiSha256 = "countdown" };
            if (kind == "content") latest = latest! with { ScrollContentRoiSha256 = "changed" };
            if (kind == "scene") latest = latest! with { SceneRoiSha256 = "changed" };
            if (kind == "missing") latest = latest! with { ScrollContentRoiSha256 = "" };
            var scroll = Command("SCROLL_DOWN", 2);
            foreach (var key in new[] { "sourceLeaseId", "pixelSha256" }) scroll[key] = saved![key]!.DeepClone();
            scroll["savedCaptureId"] = proofs[0].CaptureId; scroll["stableCaptureId"] = proofs[1].CaptureId;
            lease.Handle(scroll);
            Check(calls == (kind == "countdown" ? 1 : 0), kind + " actual lease boundary, inert adapter");
        }
        // Identical independent SOURCE frames must both survive evidence-only collection.
        foreach (var retain in new[] { false, true }) {
            long now = 100_000_000_000; var events = new List<JsonObject>();
            using var lease = new WarehouseEvidenceLease(Path.Combine(root, "retain-" + retain), "offline", events.Add,
                () => now, capturePolicy: CapturePolicy.Delivery);
            var target = new JsonObject { ["targetHwnd"] = 123L };
            lease.UpdateContext(new("r", target, "map", 4, 3, true, true, now + 70_000_000_000, 1));
            JsonObject Cmd(string op, int ordinal) => new() {
                ["type"] = WarehouseEvidenceLease.ControlType, ["schemaVersion"] = WarehouseEvidenceLease.SchemaV2,
                ["operation"] = op, ["commandId"] = Guid.NewGuid().ToString("N"), ["nonce"] = "n" + ordinal,
                ["observationSessionId"] = "offline", ["reviewSessionId"] = "review", ["reviewGeneration"] = 1,
                ["recordStableKey"] = "r", ["matchGeneration"] = 1L, ["expectedTargetInstance"] = target.DeepClone(),
                ["leaseToken"] = lease.LeaseToken, ["requestOrdinal"] = ordinal, ["remainingPages"] = 16,
                ["remainingPngBytes"] = 64L * 1024 * 1024, ["pngEncoding"] = WarehouseEvidenceLease.PngEncoding,
                ["allowWindowScroll"] = false, ["retainIndependentOriginals"] = retain };
            lease.Handle(Cmd("OPEN", 0));
            for (var seq = 1; seq <= 2; seq++) {
                lease.Handle(Cmd("REQUEST_PAGE", seq)); var gate = lease.PendingRequestGateNs!.Value;
                var proof = fixture(seq, gate); now = proof.ReadbackCompletedNs + 1;
                lease.TryPublish(new(4, 3, 16, new byte[48], proof.SourceNs, proof.ReadbackCompletedNs,
                    "offline", seq, "", seq, proof, null, gate, 1), () => true);
                if ((string?)events.Last()["event"] == "SOURCE") {
                    var saved = (JsonObject)events.Last()["source"]!; var ack = Cmd("ACK_SOURCE", seq);
                    foreach (var key in new[] { "sourceLeaseId", "bmpSha256", "pixelSha256" }) ack[key] = saved[key]!.DeepClone();
                    ack["result"] = "SAVED"; lease.Handle(ack);
                }
                now += 500_000_000;
            }
            Check(events.Count(e => (string?)e["event"] == "SOURCE") == (retain ? 2 : 1), "retention opt-in " + retain);
        }
        File.WriteAllText(Path.Combine(root, "content-evidence-pass.json"), "{\"offlineOnly\":true,\"realAccuracyClaim\":false}");
    }
}
