"""Replay once-03 pixels through production collection; no game/identity IO.

Recorded originals are immutable inputs. Delivery receipts in the isolated
replay are inert fixtures, not new real SOURCE or support observations.
"""
import copy
import hashlib
import json
from pathlib import Path
import sys

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from tests.test_native_half_viewport_flow import LiveRun, OUT
from warehouse_segment_overlap import align_warehouse_segments
from warehouse_scrollbar_observation import warehouse_search_roi


def main():
    run = ROOT / 'build/native-auto-pages-20261009/real-once-03'
    manifest_path = ROOT / 'build/native-observation/trial-drafts/warehouse-intake/aedf4bd262fd424e89a6b054447a9652.json'
    manifest_bytes = manifest_path.read_bytes()
    manifest = json.loads(manifest_bytes)
    pages = manifest['pages']
    evidence_root = manifest_path.parents[1]
    def load(page, root=evidence_root):
        d = page['descriptor']
        raw = (root / d['relativePath']).read_bytes()
        assert hashlib.sha256(raw).hexdigest() == d['sha256']
        return cv2.imdecode(np.frombuffer(raw, np.uint8), cv2.IMREAD_COLOR)
    x, y, r, b = warehouse_search_roi(1920, 1080)
    frames = [load(p) for p in pages]
    crops = [f[y:b, x:r] for f in frames]
    alignment = align_warehouse_segments(crops[2], crops[3],
        prev_id=pages[2]['descriptor']['evidenceId'], next_id=pages[3]['descriptor']['evidenceId'], required_direction='DOWN')
    # Independent prior measurement in the accepted real-run report, not an
    # expectation generated by the production matcher under test.
    assert alignment['status'] == 'VERIFIED' and alignment['verticalOffsetPx'] == -271, alignment
    assert alignment['supportCount'] >= 2 and .50 < alignment['overlapRatio'] < .53
    reverse = align_warehouse_segments(crops[3], crops[2], required_direction='DOWN')
    assert reverse['status'] == 'CONFLICT' and reverse['reason'] == 'DIRECTION_MISMATCH', reverse
    f = LiveRun()
    try:
        f.deliver(frames[1]); f.tick(); f.deliver(frames[2])
        assert f.auto._phase == 'WAIT_SCROLL' and f.sent[-1]['wheelDelta'] == -1080
        f.scroll_ack(); f.tick(); f.deliver(frames[3])
        assert f.auto._active and f.auto._phase == 'WAIT_STABLE', f.logs[-3:]
        assert len(f.gate.representatives()) == 1
        assert not f.intake.pages_copy()[-1].get('contentRole')
        scrolls_before = sum(c['operation'] == 'SCROLL_DOWN' for c in f.sent)
        f.tick()
        assert f.source._state == 'REQUEST_PENDING' and f.source._pending['operation'] == 'REQUEST_PAGE'
        assert sum(c['operation'] == 'SCROLL_DOWN' for c in f.sent) == scrolls_before == 1
        continuation = {'phase': f.auto._phase, 'pendingOperation': f.source._pending['operation'],
            'requestAttempts': f.source.source_session_snapshot()['requestAttempts'],
            'savedOriginals': len(f.intake.pages_copy()), 'stableViewportCount':len(f.gate.representatives()),
            'postScrollStable':False, 'inertDeliveryProofs':True}
        f.saved_trace('real-pixels-next-support-request')
    finally:
        f.close()
    # Only representative existing real displacements; no whole 16-image run.
    once01 = json.loads((ROOT / 'build/native-auto-pages-20261009/real-once-01/run-result.json').read_text(encoding='utf-8'))
    old = []
    for i in (7, 8):
        p = once01['sources'][i]
        raw = Path(p['png']).read_bytes()
        assert hashlib.sha256(raw).hexdigest() == p['pngSha256']
        old.append(cv2.imdecode(np.frombuffer(raw,np.uint8),cv2.IMREAD_COLOR)[y:b,x:r])
    small = align_warehouse_segments(*old, required_direction='DOWN')
    assert small['status'] == 'VERIFIED' and small['verticalOffsetPx'] == -30, small
    retained = ROOT / 'build/native-content-evidence-20261009/real-once-01'
    saved14 = json.loads((retained/'evidence-result.json').read_text(encoding='utf-8'))
    older = [load(saved14['pages'][i], retained/'trial-drafts')[y:b,x:r] for i in (9,10)]
    medium = align_warehouse_segments(*older, required_direction='DOWN')
    assert medium['status'] == 'VERIFIED' and medium['verticalOffsetPx'] == -222, medium
    assert manifest_path.read_bytes() == manifest_bytes
    assert pages[3].get('contentRole') is None and manifest['state'] == 'PARTIAL'
    result = {'passed':True, 'realPair3to4':alignment, 'reverseRejected':reverse,
        'coordinatorContinuation':continuation, 'existingReal30Px':small,
        'existingReal222Px':medium, 'actualRunManifestUnchanged':True,
        'actualFourthOriginalStillUnconfirmed':True, 'realRunCoverage':'PARTIAL',
        'realGameOrInput':False, 'recognitionRun':False}
    OUT.mkdir(parents=True,exist_ok=True)
    (OUT/'real-case-result.json').write_text(json.dumps(result,indent=2),encoding='utf-8')
    print(json.dumps(result))


if __name__ == '__main__':
    main()
